version: '3'

services:

  backdraft:
    build: .
    volumes:
      - .:/opt/services/backdraft
      - static_volume:/opt/services/backdraft/static  # <-- bind the static volume
      - media_volume:/opt/services/backdraft/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/backdraft/static  # <-- bind the static volume
      - media_volume:/opt/services/backdraft/media  # <-- bind the media volume
    depends_on:
      - backdraft
    networks:
      - nginx_network

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume

